---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "aaa"
  labels: 
    app: "aaa"
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "aaa"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "aaa"
    spec: 
      containers: 
        - 
          name: "aaa"
          image: "aaa"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5










---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "aaa"
  labels: 
    app: "aaa"
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "aaa"













---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "bbb"
  labels: 
    app: "bbb"
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "bbb"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "bbb"
    spec: 
      containers: 
        - 
          name: "bbb"
          image: "bbb"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5










---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "bbb"
  labels: 
    app: "bbb"
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "bbb"














---

apiVersion: "apps/v1"
kind: "ReplicaSet"
metadata: 
  name: "testrs"
  labels: 
    app: "testrs"
  namespace: ""
  annotations: 
    msaez.io/x: "1258"
    msaez.io/y: "293"
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: "testrs"
  template: 
    metadata: 
      labels: 
        app: "testrs"
    spec: 
      containers: 
        - 
          name: "testrs"
          image: ""
          ports: 
            - 
              containerPort: 80








---

apiVersion: "v1"
kind: "Pod"
metadata: 
  name: "testpod"
  labels: 
    app: "testpod"
  namespace: ""
  annotations: 
    msaez.io/x: "1096"
    msaez.io/y: "290"
spec: 
  containers: 
    - 
      name: "testpod"
      image: ""
      ports: 
        - 
          containerPort: 80















---

apiVersion: "apps/v1"
kind: "StatefulSet"
metadata: 
  name: "testss"
  namespace: ""
  annotations: 
    msaez.io/x: "1249"
    msaez.io/y: "458"
spec: 
  selector: 
    matchLabels: 
      app: "testss"
  serviceName: "testss"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "testss"
    spec: 
      containers: 
        - 
          name: "testss"
          image: ""
          ports: 
            - 
              containerPort: 80
              name: "testss"












---

apiVersion: "apps/v1"
kind: "DaemonSet"
metadata: 
  name: "testds"
  namespace: ""
  annotations: 
    msaez.io/x: "1090"
    msaez.io/y: "464"
spec: 
  selector: 
    matchLabels: 
      name: ""
      app: "testds"
  template: 
    metadata: 
      labels: 
        name: ""
        app: "testds"
    spec: 
      containers: 
        - 
          name: "testds"
          image: ""
          ports: 
            - 
              containerPort: 80

---

apiVersion: "apps/v1"
kind: "DaemonSet"
metadata: 
  name: "testds"
  namespace: ""
  annotations: 
    msaez.io/x: "1090"
    msaez.io/y: "464"
spec: 
  selector: 
    matchLabels: 
      name: ""
      app: "testds"
  template: 
    metadata: 
      labels: 
        name: ""
        app: "testds"
    spec: 
      containers: 
        - 
          name: "testds"
          image: ""
          ports: 
            - 
              containerPort: 80


















































































































